movie/app1/urls.py
"""
URL configuration for movie project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function view
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from app1 import views
app_name="app1"

urlpatterns = [
    path('',views.home,name="home"),    #function based view
    # path('',views.home.as_view(),name="home"),  #class based view
    path('add',views.addmovie,name="add"),   #userdefined form
    # path('add1',views.addmovies1,name="add1"),  #built in forms
    # path('add1',views.addmovie.as_view(),name="add1"), #class based view
    # path('detail/<int:pk>',views.detail.as_view(),name="detail"),   #class based view
    path('detail/<int:i>',views.detail,name="detail"),
    path('delete/<int:i>',views.delete,name='delete'),
    # path('delete/<int:pk>',views.delete.as_view(),name="delete"),
    path('edit/<int:i>',views.edit,name="edit"),
    # path('edit/<int:pk>',views.edit.as_view(),name="edit"),

]

movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

movie/app1/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title=models.CharField(max_length=20)
    description=models.TextField()
    year=models.IntegerField()
    language=models.CharField(max_length=20)
    image=models.ImageField(upload_to="img",blank=True,null=True)

    def __str__(self):
        return self.title

movie/app1/forms.py
#Form definition
from django import forms
from app1.models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie #model name
        fields='__all__'   #all fields inside the model

movie/app1/views.py
from django.shortcuts import render,redirect
from app1.models import Movie



# Create your views here.
def home(request):     #FUNCTION BASED VIEW
    k=Movie.objects.all()
    return render(request,'home.html',{'movie':k})







def addmovie(request):
    if(request.method=="POST"):
        t=request.POST['t']
        d = request.POST['d']
        y = request.POST['y']
        l = request.POST['l']
        i = request.FILES['i']


        m=Movie.objects.create(title=t,description=d,year=y,language=l,image=i)
        m.save()
        return home(request)
    return render(request,'add.html')








def detail(request,i):
    k=Movie.objects.get(id=i)
    return render(request,'detail.html',{'movie':k})


def delete(request,i):
    k=Movie.objects.get(id=i)
    k.delete()
    return home(request)






def edit(request,i):
    k=Movie.objects.get(id=i)
    if(request.method=="POST"):
        k.title=request.POST['t']
        k.description=request.POST['d']
        k.year=request.POST['y']
        k.language=request.POST['l']
        if(request.FILES.get('i')==None):
            k.save()
        else:
            k.image=request.FILES.get('i')
        k.save()
        return home(request)

    return render(request,'edit.html',{'movie':k})

movie/templates/add.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<h2 class="text-center">Add Movies</h2>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
    <div class="mb-3">
  <label class="form-label">Title</label>
  <input type="text" class="form-control" name="t" placeholder="Enter The Title">
</div>
        <div class="mb-3">
  <label class="form-label">Description</label>
  <input type="text" class="form-control" name="d" placeholder="Enter The Description">
</div>
        <div class="mb-3">
  <label class="form-label">Language</label>
  <input type="text" class="form-control" name="l" placeholder="Enter The Language">
</div>
        <div class="mb-3">
  <label class="form-label">Year</label>
  <input type="number" class="form-control" name="y" placeholder="Enter The Year">
</div>
    <div class="mb-3">
  <label class="form-label">Image</label>
  <input type="file" class="form-control" name="i" >
</div>

        <div class="mb-3">

  <input type="submit" value="ADD MOVIE">
</div>

</form>
{% endblock %}

movie/templates/add1.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<div class="mx-auto w-50">
<h1 class="text-center">Add Movies</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form.as_table}}

    </table>
    <input type="submit">
</form>
</div>
{% endblock %}

movie/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Online Movie Shop</a>

    <form class="d-flex">

      <a href="{% url 'app1:add' %}" class="btn btn-outline-dark">Add Movies</a>
    </form>
  </div>
</nav>
{% block content %}
{% endblock %}

</body>
</html>

movie/templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are you want to delete this movie???
    <input type="submit">
</form>

movie/templates/detail.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<div class="container">
  <div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{movie.image.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{movie.title}}</h5>
        <p class="card-text">{{movie.description}}</p>
        <p class="card-text"><small class="text-muted">{{movie.language}}</small></p>
          <a href="{% url 'app1:edit' movie.id %}" class="btn btn-danger">Edit</a>
          <a href="{% url 'app1:delete' movie.id %}" class="btn btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>
</div>

{% endblock %}

movie/templates/edit.html
{% extends 'base.html' %}
{% load static %}



{% block content %}
<h2 class="text-center">Edit Movies</h2>
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
<!--      <table>-->
<!--  {{form.as_table}}-->
<!--    </table>-->

    <div class="mb-3">
  <label class="form-label">Title</label>
  <input type="text" class="form-control" name="t" value="{{movie.title}}" placeholder="Enter The Title">
</div>
        <div class="mb-3">
  <label class="form-label">Description</label>
  <input type="text" class="form-control" name="d" value="{{movie.description}}" placeholder="Enter The Description">
</div>
        <div class="mb-3">
  <label class="form-label">Language</label>
  <input type="text" class="form-control" name="l" value="{{movie.language}}" placeholder="Enter The Language">
</div>
        <div class="mb-3">
  <label class="form-label">Year</label>
  <input type="number" class="form-control" name="y" value="{{movie.year}}" placeholder="Enter The Year">
</div>
    <div class="mb-3">
  <label class="form-label">Image</label>
        <img src="{{movie.image.url}}" height="100px" width="100px">
  <input type="file" class="form-control" name="i" >
</div>

        <div class="mb-3">

  <input type="submit" value="Edit">
</div>

</form>
<!--    <input type="submit">-->
{% endblock %}

movie/templates/home.html
{% extends 'base.html' %}
{% load static %}



{% block content %}

<div class="container">
    <div class="row mt-5">
        {% for i in movie %}
        <div class="col-sm-4">
            <div class="card mx-auto mb-5" style="width: 18rem;">
  <img src="{{i.image.url}}" class="card-img-top" height="200px" width="100%" alt="...">
  <div class="card-body text-center">
    <h5 class="card-title">{{i.title}}</h5>
    <p class="card-text">{{i.year}}</p>
    <a href="{% url 'app1:detail' i.id %}" class="btn btn-primary">Details</a>
  </div>
</div>
        </div>
        {% endfor %}
{{name}} {{age}}

    </div>
</div>

{% endblock %}